USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS FSI_REGULATORY_COMPLIANCE
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'MAS Regulatory Compliance & Record Keeping — Singapore FSI Demo';

CREATE SCHEMA IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.RAW
    DATA_RETENTION_TIME_IN_DAYS = 3
    COMMENT = 'Landing zone: trade records, communications, regulatory filings';

CREATE SCHEMA IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.CURATED
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Enriched and flagged records for compliance review';

CREATE SCHEMA IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.AI
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Cortex Search, Bedrock compliance review, STR generation';

CREATE SCHEMA IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.APP
    COMMENT = 'Streamlit application';

CREATE WAREHOUSE IF NOT EXISTS WH_REGULATORY
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Regulatory compliance demo workloads';

GRANT USAGE ON DATABASE FSI_REGULATORY_COMPLIANCE TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE FSI_REGULATORY_COMPLIANCE TO ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE WH_REGULATORY TO ROLE ACCOUNTADMIN;
