USE ROLE ACCOUNTADMIN;
USE DATABASE FSI_REGULATORY_COMPLIANCE;
USE WAREHOUSE WH_REGULATORY;

CREATE STORAGE INTEGRATION IF NOT EXISTS FSI_DEMOS_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::__AWS_ACCOUNT_ID__:role/snowflake-fsi-demos-s3-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://sg-fsi-demos-2026/')
    COMMENT = 'Storage integration for sg-fsi-demos-2026 bucket (regulatory + payments)';

CREATE STAGE IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.RAW.REGULATORY_S3_STAGE
    URL = 's3://sg-fsi-demos-2026/regulatory/'
    STORAGE_INTEGRATION = FSI_DEMOS_S3_INTEGRATION
    FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE)
    COMMENT = 'External stage for regulatory compliance documents';

CREATE NETWORK RULE IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.AI.BEDROCK_NETWORK_RULE
    TYPE = HOST_PORT
    MODE = EGRESS
    VALUE_LIST = ('bedrock-runtime.us-west-2.amazonaws.com:443')
    COMMENT = 'Allow Snowpark to reach Amazon Bedrock runtime endpoint';

CREATE SECRET IF NOT EXISTS FSI_REGULATORY_COMPLIANCE.AI.BEDROCK_SECRET
    TYPE = GENERIC_STRING
    SECRET_STRING = '{}'
    COMMENT = 'AWS credentials for Bedrock (JSON: aws_access_key_id, aws_secret_access_key)';

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS FSI_REGULATORY_BEDROCK_EAI
    ALLOWED_NETWORK_RULES = (FSI_REGULATORY_COMPLIANCE.AI.BEDROCK_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (FSI_REGULATORY_COMPLIANCE.AI.BEDROCK_SECRET)
    ENABLED = TRUE
    COMMENT = 'External Access Integration for Amazon Bedrock (Regulatory Compliance)';
