USE ROLE ACCOUNTADMIN;
USE DATABASE FSI_REGULATORY_COMPLIANCE;
USE SCHEMA RAW;
USE WAREHOUSE WH_REGULATORY;

CREATE TABLE IF NOT EXISTS TRADE_RECORDS (
    TRADE_ID        STRING NOT NULL,
    INSTRUMENT      STRING,
    INSTRUMENT_TYPE STRING,
    SIDE            STRING,
    QUANTITY        NUMBER(18,4),
    PRICE           NUMBER(18,4),
    NOTIONAL_SGD    NUMBER(18,2),
    VENUE           STRING,
    TRADER_ID       STRING,
    TRADER_NAME     STRING,
    DEPARTMENT      STRING,
    COUNTERPARTY    STRING,
    TRADE_TS        TIMESTAMP_NTZ,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS COMMUNICATIONS (
    COMM_ID         STRING NOT NULL,
    COMM_TYPE       STRING,
    SENDER          STRING,
    SENDER_NAME     STRING,
    RECIPIENTS      STRING,
    SUBJECT         STRING,
    BODY            STRING,
    FLAGGED_KEYWORDS STRING,
    COMM_TS         TIMESTAMP_NTZ,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REGULATORY_FILINGS (
    FILING_ID       STRING NOT NULL,
    FILING_TYPE     STRING,
    TITLE           STRING,
    STATUS          STRING,
    JURISDICTION    STRING,
    FILED_DATE      DATE,
    CONTENT         STRING,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_WATCHLIST (
    EMPLOYEE_ID     STRING NOT NULL,
    EMPLOYEE_NAME   STRING,
    DEPARTMENT      STRING,
    RESTRICTION_TYPE STRING,
    RESTRICTED_INSTRUMENTS STRING,
    REASON          STRING,
    EFFECTIVE_DATE  DATE,
    EXPIRY_DATE     DATE,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS COMPLIANCE_DOCUMENTS (
    DOC_ID          STRING NOT NULL,
    DOC_TYPE        STRING,
    TITLE           STRING,
    JURISDICTION    STRING,
    EFFECTIVE_DATE  DATE,
    CONTENT         STRING,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
