USE ROLE ACCOUNTADMIN;
USE DATABASE FSI_REGULATORY_COMPLIANCE;
USE SCHEMA CURATED;
USE WAREHOUSE WH_REGULATORY;

CREATE OR REPLACE DYNAMIC TABLE ENRICHED_COMMUNICATIONS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_REGULATORY
AS
SELECT
    c.COMM_ID, c.COMM_TYPE, c.SENDER, c.SENDER_NAME, c.RECIPIENTS, c.SUBJECT, c.BODY, c.COMM_TS,
    w.EMPLOYEE_ID AS WATCHLIST_EMPLOYEE_ID, w.RESTRICTION_TYPE, w.RESTRICTED_INSTRUMENTS, w.REASON AS WATCHLIST_REASON,
    CASE
        WHEN c.FLAGGED_KEYWORDS = 'SUSPICIOUS' THEN 'FLAGGED'
        WHEN w.EMPLOYEE_ID IS NOT NULL THEN 'WATCHLIST_MATCH'
        ELSE 'CLEAN'
    END AS REVIEW_STATUS,
    CASE
        WHEN c.FLAGGED_KEYWORDS = 'SUSPICIOUS' AND w.EMPLOYEE_ID IS NOT NULL THEN 'CRITICAL'
        WHEN c.FLAGGED_KEYWORDS = 'SUSPICIOUS' THEN 'HIGH'
        WHEN w.EMPLOYEE_ID IS NOT NULL THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SEVERITY
FROM FSI_REGULATORY_COMPLIANCE.RAW.COMMUNICATIONS c
LEFT JOIN FSI_REGULATORY_COMPLIANCE.RAW.EMPLOYEE_WATCHLIST w
    ON c.SENDER = w.EMPLOYEE_ID
    AND c.COMM_TS BETWEEN w.EFFECTIVE_DATE AND COALESCE(w.EXPIRY_DATE, '2099-12-31');

CREATE OR REPLACE DYNAMIC TABLE TRADE_SURVEILLANCE
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_REGULATORY
AS
SELECT
    t.TRADE_ID, t.INSTRUMENT, t.INSTRUMENT_TYPE, t.SIDE, t.QUANTITY, t.PRICE, t.NOTIONAL_SGD,
    t.VENUE, t.TRADER_ID, t.TRADER_NAME, t.DEPARTMENT, t.COUNTERPARTY, t.TRADE_TS,
    w.RESTRICTION_TYPE, w.RESTRICTED_INSTRUMENTS, w.REASON AS WATCHLIST_REASON,
    CASE
        WHEN w.EMPLOYEE_ID IS NOT NULL AND CONTAINS(w.RESTRICTED_INSTRUMENTS, t.INSTRUMENT) THEN 'VIOLATION'
        WHEN w.EMPLOYEE_ID IS NOT NULL THEN 'WATCHLIST_TRADER'
        ELSE 'CLEAN'
    END AS COMPLIANCE_STATUS,
    CASE
        WHEN w.EMPLOYEE_ID IS NOT NULL AND CONTAINS(w.RESTRICTED_INSTRUMENTS, t.INSTRUMENT) THEN 'CRITICAL'
        WHEN w.EMPLOYEE_ID IS NOT NULL AND t.NOTIONAL_SGD > 100000 THEN 'HIGH'
        WHEN w.EMPLOYEE_ID IS NOT NULL THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SEVERITY
FROM FSI_REGULATORY_COMPLIANCE.RAW.TRADE_RECORDS t
LEFT JOIN FSI_REGULATORY_COMPLIANCE.RAW.EMPLOYEE_WATCHLIST w
    ON t.TRADER_ID = w.EMPLOYEE_ID
    AND t.TRADE_TS BETWEEN w.EFFECTIVE_DATE AND COALESCE(w.EXPIRY_DATE, '2099-12-31');

CREATE OR REPLACE DYNAMIC TABLE COMPLIANCE_EVENTS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_REGULATORY
AS
SELECT COMM_ID AS EVENT_ID, 'COMMUNICATION' AS EVENT_TYPE, SENDER AS EMPLOYEE_ID, SENDER_NAME AS EMPLOYEE_NAME,
       SUBJECT AS DESCRIPTION, SEVERITY, REVIEW_STATUS AS STATUS, COMM_TS AS EVENT_TS
FROM FSI_REGULATORY_COMPLIANCE.CURATED.ENRICHED_COMMUNICATIONS WHERE REVIEW_STATUS != 'CLEAN'
UNION ALL
SELECT TRADE_ID, 'TRADE', TRADER_ID, TRADER_NAME, INSTRUMENT || ' ' || SIDE || ' ' || QUANTITY || ' @ ' || PRICE,
       SEVERITY, COMPLIANCE_STATUS, TRADE_TS
FROM FSI_REGULATORY_COMPLIANCE.CURATED.TRADE_SURVEILLANCE WHERE COMPLIANCE_STATUS != 'CLEAN';

CREATE OR REPLACE DYNAMIC TABLE RECORD_RETENTION_STATUS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = WH_REGULATORY
AS
SELECT 'TRADE' AS RECORD_TYPE, COUNT(*) AS TOTAL_RECORDS, MIN(TRADE_TS) AS OLDEST_RECORD, MAX(TRADE_TS) AS NEWEST_RECORD,
       COUNT(CASE WHEN TRADE_TS < DATEADD('year', -5, CURRENT_TIMESTAMP()) THEN 1 END) AS RECORDS_PAST_RETENTION, 5 AS RETENTION_YEARS, 'MAS Notice 610' AS REGULATION
FROM FSI_REGULATORY_COMPLIANCE.RAW.TRADE_RECORDS
UNION ALL
SELECT 'COMMUNICATION', COUNT(*), MIN(COMM_TS), MAX(COMM_TS),
       COUNT(CASE WHEN COMM_TS < DATEADD('year', -5, CURRENT_TIMESTAMP()) THEN 1 END), 5, 'MAS Notice 610'
FROM FSI_REGULATORY_COMPLIANCE.RAW.COMMUNICATIONS
UNION ALL
SELECT 'FILING', COUNT(*), MIN(FILED_DATE)::TIMESTAMP_NTZ, MAX(FILED_DATE)::TIMESTAMP_NTZ,
       COUNT(CASE WHEN FILED_DATE < DATEADD('year', -7, CURRENT_DATE()) THEN 1 END), 7, 'MAS Notice 610'
FROM FSI_REGULATORY_COMPLIANCE.RAW.REGULATORY_FILINGS;
