-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT employee.ID AS ENTITY_ID, employee.NAME AS ENTITY_NAME,
       employee.SENIORITY, employee.DESK, employee.ON_WATCHLIST, employee.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.MESSAGE_COUNT) AS MESSAGE_COUNT,
       SUM(observation.TRADE_COUNT) AS TRADE_COUNT,
       SUM(observation.NOTIONAL_SGD) AS NOTIONAL_SGD,
       SUM(observation.ALERT_COUNT) AS ALERT_COUNT,
       SUM(observation.CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(observation.CASES_ESCALATED) AS ESCALATED_COUNT,
       SUM(observation.REVIEW_DUE) AS REVIEW_DUE,
       SUM(observation.REVIEW_COMPLETED) AS REVIEW_COMPLETED,
       100.0 * SUM(observation.CONFIRMED_COUNT) / NULLIF(SUM(observation.ALERT_COUNT), 0) AS ALERT_PRECISION_PCT,
       100.0 * SUM(observation.REVIEW_COMPLETED) / NULLIF(SUM(observation.REVIEW_DUE), 0) AS REVIEW_COMPLIANCE_PCT,
       AVG(observation.AFTER_HOURS_PCT) AS AVG_AFTER_HOURS_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.EMPLOYEE_DAILY observation
JOIN RAW.EMPLOYEES employee ON employee.ID = observation.ENTITY_ID
GROUP BY employee.ID, employee.NAME, employee.SENIORITY, employee.DESK, employee.ON_WATCHLIST, employee.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(MESSAGE_COUNT) AS MESSAGE_COUNT,
       SUM(TRADE_COUNT) AS TRADE_COUNT, SUM(NOTIONAL_SGD) AS NOTIONAL_SGD,
       SUM(ALERT_COUNT) AS ALERT_COUNT, SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       100.0 * SUM(CONFIRMED_COUNT) / NULLIF(SUM(ALERT_COUNT), 0) AS ALERT_PRECISION_PCT
FROM RAW.EMPLOYEE_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.RULE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT DETECTION_RULE, SUM(ALERT_COUNT) AS ALERT_COUNT,
       SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(CASES_ESCALATED) AS ESCALATED_COUNT,
       SUM(NOTIONAL_SGD) AS FLAGGED_NOTIONAL_SGD,
       100.0 * SUM(CONFIRMED_COUNT) / NULLIF(SUM(ALERT_COUNT), 0) AS ALERT_PRECISION_PCT
FROM RAW.EMPLOYEE_DAILY
WHERE ALERT_COUNT > 0
GROUP BY DETECTION_RULE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(ALERT_COUNT) AS ALERTS, SUM(CONFIRMED_COUNT) AS CONFIRMED,
         SUM(CASES_ESCALATED) AS ESCALATED, SUM(NOTIONAL_SGD) AS NOTIONAL,
         SUM(MESSAGE_COUNT) AS MESSAGES,
         SUM(REVIEW_DUE) AS REVIEW_DUE, SUM(REVIEW_COMPLETED) AS REVIEW_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.EMPLOYEE_DAILY
), staff AS (SELECT COUNT(*) AS EMPLOYEE_COUNT FROM RAW.EMPLOYEES),
records AS (
  SELECT 100.0 * SUM(LEAST(CAPTURED_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.RECORDKEEPING
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Alert Precision' AS TITLE,
         100.0 * CONFIRMED / NULLIF(ALERTS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Alerts Raised', ALERTS, '' FROM observations
  UNION ALL SELECT 3, 'Confirmed Breaches', CONFIRMED, '' FROM observations
  UNION ALL SELECT 4, 'Cases Escalated', ESCALATED, '' FROM observations
  UNION ALL SELECT 5, 'Notional Surveilled (SGD M)', NOTIONAL / 1e6, '' FROM observations
  UNION ALL SELECT 6, 'Communications Captured', MESSAGES, '' FROM observations
  UNION ALL SELECT 7, 'Supervisory Review Compliance', 100.0 * REVIEW_COMPLETED / NULLIF(REVIEW_DUE, 0), '%' FROM observations
  UNION ALL SELECT 8, 'Employees Monitored', EMPLOYEE_COUNT, '' FROM staff
  UNION ALL SELECT 9, 'Record Capture Coverage', COVERAGE_PCT, '%' FROM records
  UNION ALL SELECT 10, 'Channels Pending Capture', PENDING, '' FROM records
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.RULE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
