-- Conduct-breach risk scoring and alert-volume forecast over the synthetic snapshot.
-- Predicts P(confirmed policy breach in the next 7 days) per employee and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.BREACH_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, e.DESK, e.ON_WATCHLIST, e.YEARS_AT_FIRM,
       r.AFTER_HOURS_PCT, r.FLAGGED_TERM_RATE,
       AVG(r.AFTER_HOURS_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AFTER_HOURS_7D,
       SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CONFIRMED_30D,
       IFF(SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'BREACH', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.EMPLOYEE_DAILY r JOIN RAW.EMPLOYEES e ON e.ID = r.ENTITY_ID
-- Market-wide news events are not employee-driven, so they are excluded from training.
WHERE r.DETECTION_RULE <> 'Market-wide news event';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.BREACH_TRAIN AS
SELECT DESK, ON_WATCHLIST, YEARS_AT_FIRM, AFTER_HOURS_PCT, FLAGGED_TERM_RATE, AFTER_HOURS_7D, CONFIRMED_30D, LABEL
FROM ML.BREACH_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.BREACH_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, DESK, ON_WATCHLIST, YEARS_AT_FIRM, AFTER_HOURS_PCT, FLAGGED_TERM_RATE, AFTER_HOURS_7D, CONFIRMED_30D, LABEL
FROM ML.BREACH_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.BREACH_RISK_MODEL(
  INPUT_DATA => TABLE(ML.BREACH_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.BREACH_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.BREACH_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'DESK', DESK, 'ON_WATCHLIST', ON_WATCHLIST, 'YEARS_AT_FIRM', YEARS_AT_FIRM,
           'AFTER_HOURS_PCT', AFTER_HOURS_PCT, 'FLAGGED_TERM_RATE', FLAGGED_TERM_RATE,
           'AFTER_HOURS_7D', AFTER_HOURS_7D, 'CONFIRMED_30D', CONFIRMED_30D)):probability:BREACH::FLOAT AS P
  FROM ML.BREACH_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'BREACH', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'BREACH', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'BREACH', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'BREACH', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per employee (label unknown, so excluded from features).
CREATE TABLE ML.BREACH_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.BREACH_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.BREACH_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'DESK', DESK, 'ON_WATCHLIST', ON_WATCHLIST, 'YEARS_AT_FIRM', YEARS_AT_FIRM,
           'AFTER_HOURS_PCT', AFTER_HOURS_PCT, 'FLAGGED_TERM_RATE', FLAGGED_TERM_RATE,
           'AFTER_HOURS_7D', AFTER_HOURS_7D, 'CONFIRMED_30D', CONFIRMED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:BREACH::FLOAT, 4) AS BREACH_PROB_7D,
       CASE WHEN P:probability:BREACH::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:BREACH::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Bank-wide alert-volume forecast (14 days) from the daily series, for surveillance staffing.
CREATE VIEW ML.DAILY_ALERTS AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(ALERT_COUNT)::FLOAT AS ALERT_COUNT
FROM RAW.EMPLOYEE_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.ALERT_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_ALERTS),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'ALERT_COUNT'
);

CREATE TABLE ML.ALERT_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS ALERT_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.ALERT_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
